### ISSUE TITLE
Conda takes too long to install dependencies

### ISSUE THREAD

**Issue by csris** [togethercomputer/OpenChatKit#16]
**Describe the bug**
One user reported `conda env create -f environment.yml` taking over 60 minutes. We need a better solution.

**To Reproduce**
1. Run `conda env create -f environment.yml` from the root of the repo.

**Expected behavior**
Should finish in a "reasonable" amount of time.

**Comment by satpalsr** [comment]
+1 on this.

**Comment by csris** [comment]
Training ran fine. I'll update the README to suggest using Conda.

**Comment by yibeilaopo** [comment]
I removed this line first and then did the installation, and then executed
`conda install -c conda-forge nccl`
