### ISSUE TITLE
How to disable AWS_ACCESS_KEY_ID when fine tuning?

### ISSUE THREAD

**Issue by bqcao** [togethercomputer/OpenChatKit#163]
When I ran:
bash training/finetune_llama-2-7b-32k-mqa.sh 

I got this:
Error: AWS_ACCESS_KEY_ID is not set

I'm not using AWS, so how can I disable it if I don't have to set it?

Thanks!

**Comment by csris** [comment]
@justusc, please take a look.

**Comment by ChengYen-Tang** [comment]
@bqcao,
I have a temporary method.
edit `training/dist_clm_train.py`

![image](https://github.com/togethercomputer/OpenChatKit/assets/32535494/49cb5778-16ab-4f8b-9a64-c72aa9552f35)
![image](https://github.com/togethercomputer/OpenChatKit/assets/32535494/1744ae9e-53e8-4e97-8128-6b4616c088f3)
![image](https://github.com/togethercomputer/OpenChatKit/assets/32535494/1901e32f-bc48-4608-a36b-1aac24150e0d)
