### ISSUE TITLE
Newbie question. ¿Can I use this to build a chat assistant?

### ISSUE THREAD

**Issue by mgscreativa** [togethercomputer/OpenChatKit#180]
Hi! completely new to this AI things. I wonder if I can use this project (or maybe another FOOS one) to train it from all my blog contents and then build an online chat assistant that I can put into my blog web page to help blog users to get help about my blog topics (with a blog history of many years and weekly posts).

Thanks!

**Comment by orangetin** [comment]
yes you can :)

This repo has code for fine-tuning, pretraining, and inference for GPT-Neox and Llama architecture models
