### ISSUE TITLE
Exception in prepare.py

### ISSUE THREAD

**Issue by jiandam55** [togethercomputer/OpenChatKit#36]
python data/OIG/prepare.py
  File "data/OIG/prepare.py", line 27
    gzip.open(f, 'rb') as infile, 
                       ^
SyntaxError: invalid syntax

Tell me why, thank you!

**Comment by soumyajitmaity** [comment]
USE with at the begin.
import gzip
with gzip.open('/home/joe/file.txt.gz', 'rb') as f:
    file_content = f.read()

**Comment by jiandam55** [comment]
with gzip.open(f, 'rb') as infile, open(out_path, 'wb') as outfile:
        shutil.copyfileobj(infile, outfile)
After the change, it was solved. Thank you!
