### ISSUE TITLE
ResolvePackageNotFound:   - nccl=2.12.12.1

### ISSUE THREAD

**Issue by ArchaeopteryxGu** [togethercomputer/OpenChatKit#48]
When I try to creat the environment,it happens.
I run it on the Windows.

**Comment by orangetin** [comment]
Duplicate of #19 . nccl only supports Linux. Can be fixed by using WSL.

**Comment by csris** [comment]
Yep, this appears to be a dupe of #19. @ArchaeopteryxGu, can you try with WSL?
