### ISSUE TITLE
Will the pythia 7b chat base model also be released?

### ISSUE THREAD

**Issue by tilmanrpk** [togethercomputer/OpenChatKit#74]

**Comment by orangetin** [comment]
It has been released! https://huggingface.co/togethercomputer/Pythia-Chat-Base-7B

Check out the updated [docs](https://github.com/togethercomputer/OpenChatKit#chatting-with-pythia-chat-base-7b)

**Comment by csris** [comment]
Yep! Let me know if you have any questions, @tilmanrpk!
