### ISSUE TITLE
Run  OpenChatKit-cpu_support project meet one issue

### ISSUE THREAD

**Issue by yxy123** [togethercomputer/OpenChatKit#94]
Run "bash training/finetune_GPT-NeoXT-Chat-Base-20B.sh" in  OpenChatKit-cpu_support seems still need CUDA,
the detail error log as below : 
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by orangetin** [comment]
It's hard to tell what's causing the error without all the details but it looks like you either don't have Cupy installed properly or you don't have the necessary CUDA drivers.

Could you describe your setup?

Are you running this on WSL? Because I've seen this error before and I was able to fix it by installing the proper drivers.

**Comment by yxy123** [comment]
Hi,  I‘m running on Linux.  Cupy installation failure.
Conda version:  conda 4.10.1
[base]# lspci | grep VGA
01:00.1 VGA compatible controller: Matrox Electronics Systems Ltd. MGA G200EH

**Comment by orangetin** [comment]
Did you follow these instructions: https://github.com/togethercomputer/OpenChatKit#requirements for installing Cupy and the other dependencies before trying to train the model? 

You mentioned CPU support in the first comment; CPU-only can work for inference but not for training. The command you're running is for training the model, is that what you're trying to do?

**Comment by yxy123** [comment]
Yes,  I use CPU-only do trainning, you mean cpu-only couldn't support training, right?

**Comment by yxy123** [comment]
Yes,  I use CPU-only do trainning, you mean cpu-only couldn't support training, right?

**Comment by yxy123** [comment]
Got it, thanks for your support.
